/*
 * Test data strategy for MyGroup.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2020-05-22 19:46 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for MyGroup. Provides
 * test values for parameter "int id1" 
 * of method "MyGroup(int)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2020-05-22 19:46 +0800
 */
public /*@ nullable_by_default */ class MyGroup_MyGroup__int_id1__0__id1
  extends MyGroup_ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int id1".
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add local-scope int values or generators here */ });
  }
}
